module.exports = [
  {
    issue_title: "Fix bug in authentication",
    issue_text: "Auth",
    created_by: "Kan",
    assigned_to: "Kan",
    project: "checko",
    open: true,
    status_text: "Not Started",
  },
  {
    issue_title: "Bug in UI",
    issue_text: "Button not working",
    created_by: "Akash",
    project: "checko",
    assigned_to: "Joe",
    open: true,
    status_text: "In progress",
  },
  {
    issue_title: "Database connection error",
    issue_text: "App Starting",
    project: "soji",
    created_by: "Bear",
    assigned_to: "Eli",
    open: true,
    status_text: "Not started",
  },
  {
    issue_title: "Error in API",
    issue_text: "When we send GET Request with query",
    project: "checko",
    created_by: "Maple",
    assigned_to: "Akash",
    open: true,
    status_text: "In progress",
  },
  {
    issue_title: "Fix error in function",
    issue_text: "Results not matching",
    project: "daph",
    created_by: "Bale",
    assigned_to: "Bale",
    open: false,
    status_text: "Closed",
  },
];
